#!/usr/bin/env bash
# install.sh — UniSkill Auto-Integration Script
# Usage: curl -s https://uniskill.io/install.sh | bash -s -- <YOUR_TOKEN>
#
# This script:
#   1. Detects the current project directory
#   2. Creates or updates the .env file with UNISKILL_API_TOKEN
#   3. Prints a success message
#
# 使用方式：将 token 作为第一个参数传入，脚本会自动写入 .env 文件

set -e

TOKEN="${1:-}"

# 验证 token 是否提供
if [[ -z "$TOKEN" ]]; then
    echo "❌  Error: API token is required."
    echo "    Usage: curl -s https://uniskill.io/install.sh | bash -s -- <YOUR_TOKEN>"
    exit 1
fi

# 检测运行目录（优先写入当前目录的 .env）
ENV_FILE=".env"

echo ""
echo "🚀  UniSkill Auto-Integration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 若 .env 已存在，更新或追加 UNISKILL_API_TOKEN 条目
if [[ -f "$ENV_FILE" ]]; then
    # 若变量已存在则替换，否则追加
    if grep -q "^UNISKILL_API_TOKEN=" "$ENV_FILE"; then
        # macOS & Linux 兼容的 sed 替换
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^UNISKILL_API_TOKEN=.*|UNISKILL_API_TOKEN=${TOKEN}|" "$ENV_FILE"
        else
            sed -i "s|^UNISKILL_API_TOKEN=.*|UNISKILL_API_TOKEN=${TOKEN}|" "$ENV_FILE"
        fi
        echo "✅  Updated UNISKILL_API_TOKEN in existing ${ENV_FILE}"
    else
        echo "" >> "$ENV_FILE"
        echo "# UniSkill API Token — added by install.sh" >> "$ENV_FILE"
        echo "UNISKILL_API_TOKEN=${TOKEN}" >> "$ENV_FILE"
        echo "✅  Appended UNISKILL_API_TOKEN to existing ${ENV_FILE}"
    fi
else
    # 创建新的 .env 文件
    cat > "$ENV_FILE" <<EOF
# UniSkill API Token — generated by install.sh
UNISKILL_API_TOKEN=${TOKEN}
EOF
    echo "✅  Created ${ENV_FILE} with UNISKILL_API_TOKEN"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉  Setup complete! Your token has been saved."
echo "    You can now use the UniSkill API in your agent."
echo ""
echo "    Docs: https://uniskill.io/docs"
echo ""
